version: "2"
services:

  zeppelin:
    container_name: $CONTAINER_NAME
    image: $IMAGE
    environment:
      - ANONYMOUS_DENIED=true
      - DOMAIN=$DOMAIN
      - IPASERVER=$IPASERVER
      - PASSWORD=$PASSWORD
      - PROJECT=$PROJECT
      - PROXY=$PROXY
      - REALM=$REALM
      - TOOL=$TOOL
      - ZEPPELIN_ADMIN_USER=$ZEPPELIN_ADMIN_USER
      - ZEPPELIN_ADMIN_PASSWORD=$ZEPPELIN_ADMIN_PASSWORD

    ports:
       - $EXPOSED_PORT_HTTP:8080
       - $EXPOSED_PORT_HTTPS:8443
    volumes:
       - ./logs:$ZEPPELIN_HOME/logs
       - ./notebook:$ZEPPELIN_HOME/notebook
       - ./freeipa-backups:/etc/security/freeipa-backups
       - ./keytabs:/etc/security/keytabs
