version: "2"
services:

  zeppelin:
    container_name: $CONTAINER_NAME
    image: $IMAGE
    environment:
      - ANONYMOUS_DENIED=true
      - IPASERVER=$IPASERVER
      - FREEIPA_ADMIN_PASSWORD=$FREEIPA_ADMIN_PASSWORD
      - PROJECT=$PROJECT
      - PROXY=$PROXY
      - ZEPPELIN_ADMIN_USER=$ZEPPELIN_ADMIN_USER
      - ZEPPELIN_ADMIN_PASSWORD=$ZEPPELIN_ADMIN_PASSWORD
    ports:
       - $EXPOSED_PORT_HTTP:8080
       - $EXPOSED_PORT_HTTPS:8443
    volumes:
       - ./logs:$ZEPPELIN_HOME/logs
       - ./freeipa-backups:/etc/security/freeipa-backups
       - ./zeppelin-backup/notebook:$ZEPPELIN_HOME/notebook
       - ./zeppelin-backup/keytabs:/etc/security/keytabs
       - ./zeppelin-backup/interpreters/:$ZEPPELIN_HOME/interpreters/
    stop_grace_period: 30s
